name: Cube3 Website Code Linting

on:
    pull_request:
        branches: [ main, revamp ]
    push:
        branches: [ main, revamp ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "18.x"
            - name: Install latest npm verison
              run: npm install -g npm
            - name: Install client dependencies
              run: npm ci --ignore-scripts
            - name: Lint the code
              run: npm run lint